name: ReversionQuickLook
options:
  deploymentTarget:
    macOS: "12.0"
  xcodeVersion: "16.0"
settings:
  base:
    CLANG_ENABLE_MODULES: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    MACOSX_DEPLOYMENT_TARGET: "12.0"
    SWIFT_VERSION: "5.0"
targets:
  ReversionQuickLook:
    type: app-extension
    platform: macOS
    sources:
      - path: Sources
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Reversion Quick Look
        CFBundleName: ReversionQuickLook
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.quicklook.preview
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).PreviewViewController"
          NSExtensionAttributes:
            QLIsDataBasedPreview: false
            QLSupportedContentTypes:
              - net.daringfireball.markdown
            QLSupportsSearchableItems: false
    entitlements:
      path: ReversionQuickLook.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: YES
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: NO
        MARKETING_VERSION: 1.1.0
        PRODUCT_BUNDLE_IDENTIFIER: com.github.marktext.marktext.reversion-quicklook
        PRODUCT_NAME: ReversionQuickLook
        SKIP_INSTALL: YES
